### PR TITLE
Migrate google-oauth-client-jetty to Jetty 8.

### PR DESCRIPTION
**Pull request by evantill**
use `org.eclipse.jetty` instead of `org.mortbay.jetty`

### CODE REVIEW

**Comment by evantill** [comment]
I signed the CLA.

**Comment by chanseokoh** [comment]
@ejona86

**Comment by lesv** [comment]
Be careful with this, think about GAE J7 vs J8.  This should be good on J8, but not J7.

**Comment by evantill** [comment]
@lesv could you explain a bit more please ? What can I do to help on this ?

**Comment by lesv** [comment]
@evantill My comment was more to Eric or @garrettjonesgoogle as reviewers to think this through.  There are other things that depend on this, someone just needs to check them before approving the changes.  (Internal classes)

**Comment by jadekler** [comment]
We do not support jetty 8 internally. We do support `9.2.10.v20150310`. This PR could possibly be update to that version. That said, I don't have a lot of appetite to take on this without further investigation - as @lesv correctly pointed out, this may affect many dependors.

**Comment by JustinBeckwith** [comment]
Since this is over a year old, should we just close this out for now?

**Comment by jadekler** [comment]
That's a good idea. I think this kind of work would make a lot of sense in some wholesale deprecation of some JDK versions + updating of our dependencies.

**Pull request closed without merging**
